#!/usr/bin/env bash
# tools/byoc/clouds/railway.sh — Spine BYOC Railway provisioner.
#
# Founder-tier highest-priority cloud (alongside AWS). Railway is the
# fastest path from "sign up" → "Hub running" — single GraphQL API,
# managed Postgres add-on, automatic TLS, no IaC scaffolding required.
#
# Delegation model (per docs/DEPLOYMENT_SHAPES.md):
#   Customer invites `spine-ops@` Railway account to their TEAM with
#   `Admin` on a single PROJECT. Spine's automation uses a project-
#   scoped API token (resolved from vendor vault per #9).
#
# Modes (--mode):
#   service  — single Railway service (Hub container) + managed Postgres add-on.
#              Default. Vault adapter = openbao-bundled (Railway has no
#              first-class secret manager analog to Secrets Manager / KV).

SPINE_BYOC_REGION="${SPINE_BYOC_REGION:-us-west2}"   # Railway-named region
SPINE_BYOC_MODE="${SPINE_BYOC_MODE:-service}"

_rw_log() { byoc_log "[railway/${SPINE_BYOC_MODE}/${SPINE_BYOC_REGION}] $*"; }

_RW_GRAPHQL_ENDPOINT="${RAILWAY_GRAPHQL_ENDPOINT:-https://backboard.railway.app/graphql/v2}"

byoc_validate_credentials() {
  if ! command -v curl >/dev/null 2>&1; then
    BYOC_DIE_CODE=2 byoc_die "curl required for Railway provisioner"
  fi
  if [[ "${BYOC_STUB_CALLS:-0}" == "1" || "${BYOC_DRY_RUN:-0}" == "1" ]]; then
    _rw_log "STUB: would POST { me { id email } } to $_RW_GRAPHQL_ENDPOINT"
    return 0
  fi
  if [[ -z "${SPINE_BYOC_CREDENTIALS_REF:-}" ]]; then
    _rw_log "no --credentials-ref set; expecting RAILWAY_API_TOKEN in env."
    [[ -n "${RAILWAY_API_TOKEN:-}" ]] || { _rw_log "FAIL: no RAILWAY_API_TOKEN in env."; return 3; }
  fi
  # Real: resolve the token IN A SUBSHELL and pipe into curl via --header @-.
  # The token never lands in this shell's env.
  if [[ -n "${SPINE_BYOC_CREDENTIALS_REF:-}" ]]; then
    local probe
    probe="$(byoc_resolve_vault_ref "$SPINE_BYOC_CREDENTIALS_REF" | \
      curl -sS -X POST "$_RW_GRAPHQL_ENDPOINT" \
        -H "Authorization: Bearer $(cat)" \
        -H "Content-Type: application/json" \
        -d '{"query":"{ me { id email } }"}')"
    if ! grep -q '"id"' <<<"$probe"; then
      _rw_log "FAIL: GraphQL me query did not return an id. Response: $probe"
      return 3
    fi
  else
    local probe
    probe="$(curl -sS -X POST "$_RW_GRAPHQL_ENDPOINT" \
      -H "Authorization: Bearer ${RAILWAY_API_TOKEN}" \
      -H "Content-Type: application/json" \
      -d '{"query":"{ me { id email } }"}')"
    grep -q '"id"' <<<"$probe" || { _rw_log "FAIL: GraphQL me query did not return an id. Response: $probe"; return 3; }
  fi
  _rw_log "Railway API token validated."
  return 0
}

byoc_provision() {
  byoc_banner "Railway step 1/4 — Verify project access"
  byoc_run_or_stub "GraphQL: query project($SPINE_BYOC_ACCOUNT) { id name }" \
    curl -sS -X POST "$_RW_GRAPHQL_ENDPOINT" \
      -H "Authorization: Bearer <token-from-subshell>" \
      -H "Content-Type: application/json" \
      -d "{\"query\":\"{ project(id: \\\"$SPINE_BYOC_ACCOUNT\\\") { id name } }\"}"

  byoc_banner "Railway step 2/4 — Provision Postgres add-on"
  byoc_run_or_stub "GraphQL: pluginCreate(projectId, name: 'postgresql')" \
    curl -sS -X POST "$_RW_GRAPHQL_ENDPOINT" \
      -H "Authorization: Bearer <token-from-subshell>" \
      -H "Content-Type: application/json" \
      -d "{\"query\":\"mutation { pluginCreate(input: { projectId: \\\"$SPINE_BYOC_ACCOUNT\\\", name: \\\"postgresql\\\" }) { id } }\"}"

  byoc_banner "Railway step 3/4 — Deploy Hub service"
  byoc_run_or_stub "GraphQL: serviceCreate(projectId, name: 'spine-hub', source: 'spine/hub:${SPINE_HUB_VERSION}')" \
    curl -sS -X POST "$_RW_GRAPHQL_ENDPOINT" \
      -H "Authorization: Bearer <token-from-subshell>" \
      -H "Content-Type: application/json" \
      -d "{\"query\":\"mutation { serviceCreate(input: { projectId: \\\"$SPINE_BYOC_ACCOUNT\\\", name: \\\"spine-hub\\\", source: { image: \\\"spine/hub:${SPINE_HUB_VERSION}\\\" } }) { id } }\"}"

  # Set environment variables — but secret VALUES are NOT in this script.
  # They come from Railway's own variable substitution (e.g.
  # ${{Postgres.DATABASE_URL}}) which is generated by Railway and never
  # leaves Railway. Per #9, this is acceptable because the customer's
  # Railway env IS the customer's secret store at this tier (the
  # Founder-tier opt-out: customer brings own OpenBao if they want
  # vault-grade audit).
  byoc_run_or_stub "GraphQL: variableUpsert(SPINE_DATABASE_URL = '\${{Postgres.DATABASE_URL}}')" \
    curl -sS -X POST "$_RW_GRAPHQL_ENDPOINT" \
      -H "Authorization: Bearer <token-from-subshell>" \
      -H "Content-Type: application/json" \
      -d "{\"query\":\"mutation { variableUpsert(input: { projectId: \\\"$SPINE_BYOC_ACCOUNT\\\", name: \\\"SPINE_DATABASE_URL\\\", value: \\\"\\\\\${{Postgres.DATABASE_URL}}\\\" }) { id } }\"}"
  byoc_run_or_stub "GraphQL: variableUpsert(SPINE_HUB_VERSION = '${SPINE_HUB_VERSION}')" \
    curl -sS -X POST "$_RW_GRAPHQL_ENDPOINT" \
      -H "Authorization: Bearer <token-from-subshell>" \
      -H "Content-Type: application/json" \
      -d "{\"query\":\"mutation { variableUpsert(input: { projectId: \\\"$SPINE_BYOC_ACCOUNT\\\", name: \\\"SPINE_HUB_VERSION\\\", value: \\\"$SPINE_HUB_VERSION\\\" }) { id } }\"}"
  byoc_run_or_stub "GraphQL: variableUpsert(SPINE_HUB_ADMIN_EMAIL = '${SPINE_BYOC_ADMIN_EMAIL}')" \
    curl -sS -X POST "$_RW_GRAPHQL_ENDPOINT" \
      -H "Authorization: Bearer <token-from-subshell>" \
      -H "Content-Type: application/json" \
      -d "{\"query\":\"mutation { variableUpsert(input: { projectId: \\\"$SPINE_BYOC_ACCOUNT\\\", name: \\\"SPINE_HUB_ADMIN_EMAIL\\\", value: \\\"$SPINE_BYOC_ADMIN_EMAIL\\\" }) { id } }\"}"

  byoc_banner "Railway step 4/4 — Generate public domain + TLS"
  byoc_run_or_stub "GraphQL: serviceDomainCreate(serviceId) → spine-hub-<id>.up.railway.app" \
    curl -sS -X POST "$_RW_GRAPHQL_ENDPOINT" \
      -H "Authorization: Bearer <token-from-subshell>" \
      -H "Content-Type: application/json" \
      -d "{\"query\":\"mutation { serviceDomainCreate(input: { serviceId: \\\"<from-step-3>\\\" }) { domain } }\"}"

  byoc_emit_handoff \
    "https://spine-hub-${SPINE_BYOC_BUNDLE_ID:0:8}.up.railway.app" \
    "$SPINE_BYOC_ADMIN_EMAIL" \
    "Railway shared variable: SPINE_VAULT_UNSEAL_SHARES (run 'railway variables' to view ONCE)"
}

byoc_destroy() {
  byoc_banner "Railway teardown"
  byoc_run_or_stub "GraphQL: serviceDelete(spine-hub)" \
    curl -sS -X POST "$_RW_GRAPHQL_ENDPOINT" \
      -H "Authorization: Bearer <token-from-subshell>" \
      -H "Content-Type: application/json" \
      -d "{\"query\":\"mutation { serviceDelete(id: \\\"<spine-hub-service-id>\\\") }\"}"
  byoc_run_or_stub "GraphQL: pluginDelete(postgresql)" \
    curl -sS -X POST "$_RW_GRAPHQL_ENDPOINT" \
      -H "Authorization: Bearer <token-from-subshell>" \
      -H "Content-Type: application/json" \
      -d "{\"query\":\"mutation { pluginDelete(id: \\\"<postgres-plugin-id>\\\") }\"}"
  _rw_log "Railway teardown complete. Project remains; customer revokes spine-ops invite to fully detach."
}
