#!/usr/bin/env bash
# tools/hub-up.sh — laptop-dev wrapper that brings up the Hub via
# docker compose with the right SPA build path for the host platform.
#
# On Linux + on customer-cloud CI, the in-Docker spa-builder stage builds
# the SPA without issue. On Docker Desktop for macOS (Apple Silicon),
# esbuild hits two upstream bugs (`lfstack.push` panic on slim images;
# `service was stopped` on full images) that we can't engineer around
# without esbuild fixes. This wrapper:
#
#   1. Detects Docker Desktop on macOS
#   2. If so, builds the SPA on the host first (`npm run build`) and
#      passes the resulting dist/ via buildx --build-context spa-dist=...
#   3. Otherwise builds normally inside Docker via the spa-builder stage
#
# Either way, the Hub image is tagged `spine/hub:v3-dev` so the docker
# compose `image:` directive picks it up.
#
# Usage:
#   bash tools/hub-up.sh                 # build + up -d
#   bash tools/hub-up.sh --rebuild       # force image rebuild
#   bash tools/hub-up.sh --down          # tear down + remove volumes
#   bash tools/hub-up.sh --status        # show container status

set -euo pipefail

readonly REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${REPO_ROOT}"

readonly COMPOSE_FILE="hub/docker-compose.yml"
readonly ENV_FILE="$(mktemp -t spine-hub-up.XXXXXX.env)"
readonly IMAGE_TAG="spine/hub:v3-dev"

cleanup() { rm -f "${ENV_FILE}"; }
trap cleanup EXIT

# --- platform detection -----------------------------------------------------
host_needs_prebuilt_spa() {
  if [[ "$(uname -s)" == "Darwin" ]] && command -v docker >/dev/null \
     && docker version --format '{{.Server.Os}}' 2>/dev/null | grep -q '^linux$'; then
    # macOS host + Linux engine = Docker Desktop. Always pre-build to
    # dodge the esbuild bugs.
    return 0
  fi
  return 1
}

# --- write a smoke env-file (matches hub/tests/test-hub-up.sh pattern) ------
write_env_file() {
  cat >"${ENV_FILE}" <<EOF
# Auto-generated by tools/hub-up.sh — do NOT commit.
# Smoke-test placeholders; spine-hub-vault writes real values when the
# Day-0 wizard runs (out of scope for this dev loop).
SPINE_HUB_HOST_PORT=8090
SPINE_HUB_DEV=1
SPINE_HUB_LOG_LEVEL=info
SPINE_DB_HOST_PORT=33099
SPINE_DB_PASSWORD=smoke-test-db-pw
KEYCLOAK_DB_PASSWORD=smoke-test-kc-db-pw
KEYCLOAK_ADMIN_PASSWORD=smoke-test-kc-admin-pw
SPINE_VAULT_ROLE_ID=smoke-test-role-id
SPINE_VAULT_SECRET_ID_WRAPPED=smoke-test-wrapped-secret-id
# LLM provider keys — pulled from host shell env (export
# ANTHROPIC_API_KEY=... before running hub-up.sh). Required for the
# intake role + downstream agents to actually call out.
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
OPENAI_API_KEY=${OPENAI_API_KEY:-}
EOF
}

# --- build SPA on host (when needed) ----------------------------------------
build_spa_on_host() {
  echo "[hub-up] Docker Desktop on macOS — building SPA on host to dodge esbuild bug"
  pushd shared/ui/spa >/dev/null
  if [[ ! -d node_modules ]]; then
    npm install --no-audit --no-fund
  fi
  # SPA_BASE_PATH must match the Hub's mount prefix (shared/api/app.py
  # serves the SPA at /spa/*). Without this, SvelteKit emits absolute
  # /_app/... asset URLs that 404 against the catch-all route.
  SPA_BASE_PATH=/spa npm run build
  popd >/dev/null
  if [[ ! -f shared/ui/spa/dist/index.html ]]; then
    echo "[hub-up] FATAL: SPA build did not produce dist/index.html" >&2
    exit 1
  fi
}

# --- build hub image --------------------------------------------------------
build_image() {
  if host_needs_prebuilt_spa; then
    build_spa_on_host
    echo "[hub-up] building image with host SPA via buildx --build-context"
    docker buildx build \
      --build-context spa-dist=shared/ui/spa/dist \
      -t "${IMAGE_TAG}" \
      -f hub/Dockerfile \
      --load \
      .
  else
    echo "[hub-up] building image with in-Docker spa-builder stage"
    docker buildx build \
      -t "${IMAGE_TAG}" \
      -f hub/Dockerfile \
      --load \
      .
  fi
}

# --- main -------------------------------------------------------------------
action="${1:-up}"
case "${action}" in
  --down|down)
    # Stop containers but preserve volumes — projects survive --down/--up.
    # Use --reset to wipe everything.
    write_env_file
    docker compose -f "${COMPOSE_FILE}" --env-file "${ENV_FILE}" down
    ;;
  --status|status)
    docker ps --format '{{.Names}}\t{{.Status}}' | grep -E '^spine-hub' || true
    ;;
  --rebuild|rebuild)
    # NOTE: only stops + removes containers; volumes survive so projects
    # persist across image rebuilds. Use `--reset` if you actually want
    # to wipe the DB + start fresh.
    write_env_file
    docker compose -f "${COMPOSE_FILE}" --env-file "${ENV_FILE}" down
    build_image
    docker compose -f "${COMPOSE_FILE}" --env-file "${ENV_FILE}" up -d
    echo "[hub-up] Hub coming up — give it ~30s; then browse http://localhost:8090/spa/"
    ;;
  --reset|reset)
    write_env_file
    docker compose -f "${COMPOSE_FILE}" --env-file "${ENV_FILE}" down -v
    build_image
    docker compose -f "${COMPOSE_FILE}" --env-file "${ENV_FILE}" up -d
    echo "[hub-up] Hub coming up FRESH (volumes wiped) — ~30s; browse http://localhost:8090/spa/"
    ;;
  --up|up|"")
    write_env_file
    # Build only if image absent.
    if ! docker image inspect "${IMAGE_TAG}" >/dev/null 2>&1; then
      build_image
    fi
    docker compose -f "${COMPOSE_FILE}" --env-file "${ENV_FILE}" up -d
    echo "[hub-up] Hub coming up — give it ~30s; then browse http://localhost:8090/spa/"
    ;;
  -h|--help)
    sed -n '1,30p' "${BASH_SOURCE[0]}"
    ;;
  *)
    echo "[hub-up] unknown action: ${action} (try --help)" >&2
    exit 64
    ;;
esac
