"""Proposal-style `.tron/*` layout for PLAN mode (dict, on-disk, or both)."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterator, List, Tuple


def iter_tron_plan_files(
    *,
    project_id: str,
    project_name: str,
    repo_url: str,
    default_branch: str,
    goals: str,
    constraints: str,
    artifact: dict[str, Any],
    questionnaire: dict[str, Any] | None = None,
) -> Iterator[Tuple[str, str]]:
    """Yield ``(relative_path, utf-8 body)`` pairs for the Tron plan bundle."""
    now = datetime.now(timezone.utc).isoformat()
    project_json = {
        "tron_plan_version": 1,
        "project_id": project_id,
        "name": project_name,
        "repo_url": repo_url,
        "default_branch": default_branch,
        "goals": goals,
        "constraints": constraints,
        "generated_at": now,
        "source": "tron-plan-workflow",
        "has_questionnaire": bool(questionnaire),
    }
    yield ".tron/project.json", json.dumps(project_json, indent=2) + "\n"

    if questionnaire:
        yield ".tron/questionnaire.json", json.dumps(questionnaire, indent=2) + "\n"

    arch = artifact.get("architecture_summary") or ""
    yield ".tron/architecture.md", f"# Architecture\n\n{arch}\n"

    bullets = artifact.get("requirements_bullets") or []
    if isinstance(bullets, list):
        body = "\n".join(f"- {b}" for b in bullets if b is not None)
    else:
        body = str(bullets)
    yield ".tron/requirements.md", f"# Requirements\n\n{body}\n"

    gates = artifact.get("quality_gates_suggested")
    if gates is None:
        gates = artifact.get("merged_default_gates") or {}
    yield ".tron/quality-gates.json", json.dumps(gates, indent=2) + "\n"

    tests = artifact.get("test_plan_outline") or []
    if isinstance(tests, list):
        tbody = "\n".join(f"- {t}" for t in tests if t is not None)
    else:
        tbody = str(tests)
    yield ".tron/test-specifications.md", f"# Test specifications\n\n{tbody}\n"

    risks = artifact.get("risks") or []
    if isinstance(risks, list) and risks:
        rbody = "\n".join(f"- {r}" for r in risks if r is not None)
        yield ".tron/risks.md", f"# Risks\n\n{rbody}\n"

    readme = (
        "# Tron plan bundle\n\n"
        "Generated by Tron PLAN mode. Commit these files to pin architecture, "
        "requirements, quality gates, and test expectations for audits and builds.\n"
    )
    yield ".tron/README.md", readme

    skill_md = (
        "# Tron project context\n\n"
        f"Project: **{project_name}** (`{project_id}`).\n\n"
        "Read `.tron/architecture.md`, `.tron/requirements.md`, and "
        "`.tron/quality-gates.json` before suggesting changes.\n"
    )
    yield ".cursor/skills/tron-project.md", skill_md


def build_tron_plan_files_dict(
    *,
    project_id: str,
    project_name: str,
    repo_url: str,
    default_branch: str,
    goals: str,
    constraints: str,
    artifact: dict[str, Any],
    questionnaire: dict[str, Any] | None = None,
) -> Dict[str, str]:
    """Return ``relative_path -> file body`` (forward slashes)."""
    return {
        rel: content
        for rel, content in iter_tron_plan_files(
            project_id=project_id,
            project_name=project_name,
            repo_url=repo_url,
            default_branch=default_branch,
            goals=goals,
            constraints=constraints,
            artifact=artifact,
            questionnaire=questionnaire,
        )
    }


def write_tron_bundle_to_dir(repo_root: str | Path, bundle: Dict[str, str]) -> List[str]:
    """Write a bundle produced by :func:`build_tron_plan_files_dict`."""
    root = Path(repo_root).resolve()
    written: list[str] = []
    for rel, content in bundle.items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(rel.replace("\\", "/"))
    return written


def write_tron_plan_bundle(
    repo_root: str | Path,
    *,
    project_id: str,
    project_name: str,
    repo_url: str,
    default_branch: str,
    goals: str,
    constraints: str,
    artifact: dict[str, Any],
) -> List[str]:
    """Create `.tron/` under ``repo_root``; returns relative paths."""
    bundle = build_tron_plan_files_dict(
        project_id=project_id,
        project_name=project_name,
        repo_url=repo_url,
        default_branch=default_branch,
        goals=goals,
        constraints=constraints,
        artifact=artifact,
        questionnaire=artifact.get("questionnaire") if isinstance(artifact, dict) else None,
    )
    return write_tron_bundle_to_dir(repo_root, bundle)
